services:
  - type: web
    name: ecommerce2
    env: docker
    region: oregon
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        scope: project
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.us-east-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: ecommerce_db
      - key: DB_USERNAME
        scope: project
      - key: DB_PASSWORD
        scope: project
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: your_mail_host # ¡ACTUALIZA ESTO! e.g., smtp.mailtrap.io
      - key: MAIL_PORT
        value: "587" # ¡ACTUALIZA ESTO! e.g., 2525 o 587
      - key: MAIL_USERNAME
        scope: project # ¡ACTUALIZA ESTO en Render!
      - key: MAIL_PASSWORD
        scope: project # ¡ACTUALIZA ESTO en Render!
      - key: MAIL_ENCRYPTION
        value: tls # O ssl, dependiendo de tu proveedor
      - key: MAIL_FROM_ADDRESS
        value: noreply@example.com # ¡ACTUALIZA ESTO!
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}" # O el nombre que desees
    preDeployCommand: >
      php artisan migrate:fresh --seed --force &&
      php artisan cache:clear &&
      php artisan config:clear &&
      php artisan route:clear &&
      php artisan view:clear
