services:
  - type: web
    name: ecommerce2
    env: docker
    region: oregon
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        scope: project
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.us-east-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: ecommerce_db
      - key: DB_USERNAME
        scope: project
      - key: DB_PASSWORD
        scope: project
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
    preDeployCommand: >
      php artisan migrate --force &&
      php artisan db:seed --force || true &&
      php artisan cache:clear &&
      php artisan config:clear &&
      php artisan route:clear &&
      php artisan view:clear
